### ISSUE TITLE
Restrict Inventory transporters

### ISSUE THREAD

**Issue by Pyromanc3r** [VintageModsReforged/VintageBarrels#3]
Is it possible to add a setting that prohibits putting these items in backpacks? So that there is no temptation to do such things...
![2024-12-19_16 06 49](https://github.com/user-attachments/assets/6ae1add3-55bd-45df-97bd-fe82a6833ba5)

This is the backpack from `Project: Red`. You can do the same with the `Backpack` mod (but in this mod you can prohibit the necessary item IDs in the config).
Maybe even limit only 1 Transporter in the player's inventory. Still I think this thing is supposed to transfer chests to a small distance, not a long journey.

**Comment by CrossVas** [comment]
A brut solution would be to prevent any inventory from opening when you have a full transporter. That would mean only 9 available slots. Also you won't be able to store full transporters inside chests/other inventories (because you can't open them)

UPD: Or I can whitelist the player inventory only to be able to open

**Comment by CrossVas** [comment]
And to go even further, I can prevent full transporters from being tossable, so you can't use hoppers or any pick-up blocks to store and transport them

**Comment by CrossVas** [comment]
So we have: 
1. Prevent `ANY` inventories from opening, leaving only 9 possible slots for transportation (the hotbar);
2. Prevent `ONLY` inventories that aren't `Player Inventory`, leaving us with full player inventory for transportation; (I vote for this)
3. Make a config with a list of whitelisted gui classes that are available for opening (not my favorite).

**Comment by Pyromanc3r** [comment]
Do as you see fit. :)

**Comment by CrossVas** [comment]
Restricted any inventories that aren't Player Inventory from opening. I won't go any further and mess with inventories, because that's out of scope for this mods. For now, any portable inventories are blocked (backpacks, etc.).
While there are still ways to carry lots of full transporters, I don't think this is something this mod should address. Hope you understand.
